### ISSUE TITLE
Class google not work

### ISSUE THREAD

**Issue by x1Lenny** [kitUIN/PicImageSearch#56]
google search doesn't work.
Your library uses https://www.google.com/searchbyimage
but that url doesn't work, you need to search google lens.

I would also like to see yandex image search in your library, searches by image better than google, consider this option ^^

examples(for url)
Image URL: https://i1.sndcdn.com/avatars-000248291936-634zqi-t500x500.jpg
Google: https://lens.google.com/uploadbyurl?url=https://i1.sndcdn.com/avatars-000248291936-634zqi-t500x500.jpg
Yandex: https://yandex.com/images/search?rpt=imageview&url=https://i1.sndcdn.com/avatars-000248291936-634zqi-t500x500.jpg
TinEye: https://tineye.com/search?url=https://i1.sndcdn.com/avatars-000248291936-634zqi-t500x500.jpg
Bing: https://www.bing.com/images/searchbyimage?cbir=sbi&imgurl=https://i1.sndcdn.com/avatars-000248291936-634zqi-t500x500.jpg

I don't know how to do it for the files, but it would be very useful

**Comment by NekoAria** [comment]
You can now upgrade to v3.8.0 by using "pip install -U PicImageSearch", and then try the code above.

In addition, I tried to support Yandex again, but unfortunately triggered Yandex SmartCaptcha. To bypass it, we may need to use a headless browser, but that conflicts with the lightweight positioning of this library, so I had to put it on hold.

**Comment by NekoAria** [comment]
Now Yandex is supported, but due to dependency changes, you need to install `httpx` by using `pip install httpx` .

Since the Google image reverse search is currently unavailable, I cannot test the related refactoring of the function `goto_page()` , so I will put it on hold for now and look at it again tomorrow.

**Comment by x1Lenny** [comment]
I am not an English-speaker too, but I can advise you deepl.com translator, according to my observations it works better than google translator

**Comment by x1Lenny** [comment]
A day ago I had this code working. Now it's not working, why? I didn't change my IP, I didn't change the code either. Before it gave out 5 pages on the image, now it's 1 blank. When I do a manual search for a photo, it works fine. Any idea why this is happening?
```
Async with Network() as client:
            google = google(client=client)
            results = await google.search(file=photo_file)
            logger.info(results.origin)
```

**Comment by NekoAria** [comment]
Please try the latest `v3.9.0` .

**Comment by NekoAria** [comment]
The reason why you are encountering this problem is due to your network environment,
either you use or do not use a proxy, or you configure the headers and cookies obtained in your browser,
which may be helpful, but I am not sure, because there is no particularly good way to deal with anti-crawling techniques.
