### ISSUE TITLE
Ascii2d need selected.websource

### ISSUE THREAD

**Issue by LittleApple-fp16** [kitUIN/PicImageSearch#86]
I would like to have a built-in string to display what social media site the item comes from.
Example: selected.websource should display 'Twitter' or 'pixiv'

**Comment by NekoAria** [comment]
The previous version included an attribute named `mark`, which is the gray source website marker you can see on ascii2d.
However, I felt that this was not very effective. It's better to directly parse the domain of the returned `selected.url` to identify the source website. This is because the number of websites that can be identified through `mark` is limited, and some are in Japanese. Specifically, in most cases, these are the ones included in `SUPPORTED_SOURCES` :

```
SUPPORTED_SOURCES = ["pixiv", "twitter", "fanbox", "fantia", "ニコニコ静画", "ニジエ"]
```

**Comment by LittleApple-fp16** [comment]
Okay, I understand what you mean.
